schema_version = 2
package = "/home/kalex/rackforge/plugins/rf-dls"
data_root = "/home/kalex/rackforge/data"
preset = "gm.piano-1"

[resources]
dls-bank = "/home/kalex/rackforge/data/plugins/rf-dls/banks/gm.dls"

[audio.output]
fallback = "none"
sample_format = "s32_le"
sample_rate_hz = 48000
channels = 2
period_frames = 128
buffer_frames = 384

[audio.output.device]
mode = "usb"
vendor_id = 0x1235
product_id = 0x8211
