"""Draws the RackForge nameplate: the RF mark with the word set beneath it.

The lockup is the logo as the interface presents it — mark over word, flush
left, on a plate of its own.

The wordmark is outlined from the same Barlow Semi Condensed the interface
loads, at the same proportion the rail sets it — 13px of type under a 140px
mark, 9px apart — so the asset and the running app are the same lockup at
different sizes.

Earlier the logo carried no word, because hand-drawn outlines drift from the
typeface the moment the interface changes weight. Outlines that are generated
cannot drift: rerun this script and they follow the font. That is the whole
reason it exists rather than an editor's export sitting in the tree.

Usage: python tools/generate-brand-logo.py
"""

from __future__ import annotations

import re
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

REPOSITORY = Path(__file__).resolve().parent.parent
BRAND = REPOSITORY / "assets" / "brand"
FONT = REPOSITORY / "web" / "public" / "fonts" / "BarlowSemiCondensed-Bold.ttf"

WORD = "RACKFORGE"
NEWLINE = chr(10)
# The rail's own numbers: font-size 13px, letter-spacing 0.16em, gap 9px,
# under a mark 140px wide. Expressed against the mark's 704-unit measure so
# the lockup holds at any size.
MARK_WIDTH = 704.0
MARK_HEIGHT = 308.0
TYPE_SIZE = MARK_WIDTH * 13.0 / 140.0
TRACKING = 0.16
GAP = MARK_WIDTH * 9.0 / 140.0

# The word is a single ink, so unlike the mark it cannot survive a ground it
# did not choose: on a light card while the system is dark it renders cream on
# cream. The lockup therefore carries its own plate, the way rackforge-logo.svg
# does, and the pair flips together. Artwork that needs no plate is the mark.
PLATE_DAYLIGHT = "#ebe4d8"
PLATE_STAGE = "#212327"
INK_DAYLIGHT = "#221e1a"
INK_STAGE = "#efe9de"

# The clear space rackforge-logo.svg already measures in around the mark.
CLEAR_X = 148.0
CLEAR_Y = 76.0


def wordmark() -> tuple[str, float, float, float]:
    """Returns the word as one path, its ink width, cap height and bearing."""
    font = TTFont(FONT)
    upem = font["head"].unitsPerEm
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    advances = font["hmtx"].metrics

    scale = TYPE_SIZE / upem
    tracking = TRACKING * TYPE_SIZE

    pen = SVGPathPen(glyphs, ntos=lambda value: f"{value:.2f}")
    bounds = BoundsPen(glyphs)
    pen_x = 0.0
    for index, character in enumerate(WORD):
        name = cmap[ord(character)]
        # y flips because glyph space counts upward and SVG counts downward.
        placement = Transform(scale, 0, 0, -scale, pen_x, 0)
        glyphs[name].draw(TransformPen(pen, placement))
        glyphs[name].draw(TransformPen(bounds, placement))
        pen_x += advances[name][0] * scale
        # Tracking sits between letters only: a trailing space would push the
        # word off its own left-flush edge.
        if index != len(WORD) - 1:
            pen_x += tracking

    left, top, right, bottom = bounds.bounds
    # All caps, so the ink bounds are the cap height exactly. The R carries a
    # left side bearing, so the drawn path starts inside its own advance;
    # shifting by that bearing is what makes the word flush with the mark
    # rather than a hair short of it. The block is measured, not eyeballed.
    path = pen.getCommands()
    return path, right - left, bottom - top, left


def mark_body() -> str:
    """The mark's own markup, verbatim: the paint order is the drawing."""
    source = (BRAND / "rackforge-mark.svg").read_text(encoding="utf-8")
    body = re.search(r"<svg[^>]*>(.*)</svg>", source, re.DOTALL)
    if body is None:
        raise SystemExit("rackforge-mark.svg is not the shape this script expects")
    # The nested artwork must not bring its own title and desc: two
    # elements sharing an id is invalid, and the lockup names itself.
    inner = body.group(1)
    for tag in ("title", "desc"):
        inner = re.sub(f"<{tag}[^>]*>.*?</{tag}>", "", inner, flags=re.DOTALL)
    indent = NEWLINE + "    "
    return indent.join(
        line.strip() for line in inner.strip().splitlines() if line.strip()
    )


def main() -> None:
    path, word_width, cap_height, bearing = wordmark()
    width = CLEAR_X * 2 + MARK_WIDTH
    height = CLEAR_Y * 2 + MARK_HEIGHT + GAP + cap_height
    baseline = CLEAR_Y + MARK_HEIGHT + GAP + cap_height
    document = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.0f} {height:.0f}" role="img" aria-labelledby="title description">
  <title id="title">RackForge</title>
  <desc id="description">The RF monogram over the RackForge wordmark.</desc>

  <!-- GENERATED by tools/generate-brand-logo.py. The wordmark is outlined from
       web/public/fonts/BarlowSemiCondensed-Bold.ttf at the proportion the
       interface's rail sets it: 13px of type under a 140px mark, 9px apart.
       Edit the script, not this file.

       PAINT ORDER IS THE DRAWING inside the mark below; see rackforge-mark.svg. -->

  <style>
    svg {{ --plate: {PLATE_DAYLIGHT}; --ink: {INK_DAYLIGHT}; }}
    @media (prefers-color-scheme: dark) {{
      svg {{ --plate: {PLATE_STAGE}; --ink: {INK_STAGE}; }}
    }}
  </style>

  <rect width="{width:.0f}" height="{height:.0f}" fill="var(--plate)"/>

  <svg x="{CLEAR_X:.0f}" y="{CLEAR_Y:.0f}" width="{MARK_WIDTH:.0f}" height="{MARK_HEIGHT:.0f}" viewBox="0 0 {MARK_WIDTH:.0f} {MARK_HEIGHT:.0f}">
    {mark_body()}
  </svg>

  <g transform="translate({CLEAR_X - bearing:.2f} {baseline:.2f})" fill="var(--ink)">
    <path d="{path}"/>
  </g>
</svg>
"""
    destination = BRAND / "rackforge-lockup.svg"
    destination.write_text(document, encoding="utf-8")
    print(
        f"nameplate: {width:.0f}x{height:.0f} plate, "
        f"word {word_width:.1f} wide over a cap height of {cap_height:.1f}"
    )


if __name__ == "__main__":
    main()
