//! Regenerates `apps/rackforge-desktop/src/midi2_sdk.rs` from the Windows MIDI
//! Services App SDK metadata. Only the classes the desktop uses are asked for;
//! `windows-bindgen` pulls what they depend on. Run from the repository root.

const WINMD: &str = r"C:/Program Files/Windows MIDI Services/Desktop App SDK Runtime/Microsoft.Windows.Devices.Midi2.winmd";
const OUT: &str = "apps/rackforge-desktop/src/midi2_sdk.rs";
const HEADER: &str = "// Bindings for the Windows MIDI Services App SDK (`Microsoft.Windows.Devices.Midi2`),\n// generated by `tools/midi2-sdk-bindgen` from the winmd the SDK runtime installs at\n// `C:/Program Files/Windows MIDI Services/Desktop App SDK Runtime/`. Do not edit;\n// regenerate with `cargo run --manifest-path tools/midi2-sdk-bindgen/Cargo.toml`.\n// SDK: Release Candidate 4, 1.0.17-rc.4.25.\n\n";

fn main() {
    let log = windows_bindgen::bindgen([
        "--in", WINMD, "--in", "default", "--out", OUT,
        "--filter",
        "Microsoft.Windows.Devices.Midi2.MidiSession",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointConnection",
        "Microsoft.Windows.Devices.Midi2.MidiMessageReceivedEventArgs",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformation",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceWatcher",
        "Microsoft.Windows.Devices.Midi2.MidiClock",
        "Microsoft.Windows.Devices.Midi2.MidiSendMessageResults",
        "Microsoft.Windows.Devices.Midi2.MidiMessageStruct",
        "Microsoft.Windows.Devices.Midi2.IMidiUniversalPacket",
        "Microsoft.Windows.Devices.Midi2.MidiSystemTimerSettings",
        "Microsoft.Windows.Devices.Midi2.IMidiEndpointMessageProcessingPlugin",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointConnectionBasicSettings",
        "Microsoft.Windows.Devices.Midi2.MidiMessageType",
        "Microsoft.Windows.Devices.Midi2.MidiPacketType",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointDevicePurpose",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformationFilters",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformationSortOrder",
        "Microsoft.Windows.Devices.Midi2.MidiEndpointAssociatedPortDeviceInformation",
        "Microsoft.Windows.Devices.Midi2.Midi1PortFlow",
        "Microsoft.Windows.Devices.Midi2.MidiGroup",
        "--reference", "windows,skip-root,Windows",
    ]);
    let generated = std::fs::read_to_string(OUT).expect("generated bindings");
    std::fs::write(OUT, format!("{HEADER}{generated}")).expect("write bindings");
    print!("{log}");
}
